#ifndef NFS_FILE_SERVER_MESSAGETYPES_H
#define NFS_FILE_SERVER_MESSAGETYPES_H
#include "CloseReply.h"
#include "ConnectReply.h"
#include "ErrorReply.h"
#include "FstatReply.h"
#include "LseekReply.h"
#include "OpenReply.h"
#include "ReadReply.h"
#include "UnlinkReply.h"
#include "WriteReply.h"
#include "CloseRequest.h"
#include "ConnectRequest.h"
#include "FstatRequest.h"
#include "LseekRequest.h"
#include "OpenRequest.h"
#include "ReadRequest.h"
#include "UnlinkRequest.h"
#include "WriteRequest.h"

#endif //NFS_FILE_SERVER_MESSAGETYPES_H
